1. Implement logistic regression using Python/R to perform classification on
Social_Network_Ads.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision,
Recall on the given dataset.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error,accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score

In [2]:
df = pd.read_csv(r"C:\Users\Niraj More\OneDrive\Desktop\DSBDA\Practice\PR_EXAM_DATASET\Social_Network_Ads.csv")

In [3]:
df

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

## Implement logistic regression using Python/R to perform classification on Social_Network_Ads.csv dataset.

In [4]:
df['Gender']= df['Gender'].replace({'Male':1,'Female':0})

In [5]:
df

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510       1  19.0          19000.0          0
1    15810944       1  35.0          20000.0          0
2    15668575       0  26.0          43000.0          0
3    15603246       0  27.0          57000.0          0
4    15804002       1  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0          41000.0          1
396  15706071       1  51.0          23000.0          1
397  15654296       0  50.0          20000.0          1
398  15755018       1  36.0          33000.0          0
399  15594041       0  49.0          36000.0          1

[400 rows x 5 columns]

In [6]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [7]:

x=df[['User ID', 'Gender', 'Age', 'EstimatedSalary']]
y=df['Purchased']

In [8]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state = 1)

In [9]:
xtrain.shape

(320, 4)

In [10]:
ytrain.shape

(320,)

In [11]:
xtest.shape

(80, 4)

In [12]:
model = LogisticRegression()

In [13]:
model.fit(xtrain,ytrain)

LogisticRegression()

In [14]:
ypred = model.predict(xtest)

In [15]:
ypred

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [16]:
accuracy_score(ytest,ypred)

0.7125

In [17]:
ytest.values

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

## Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on the given dataset.

In [18]:
confusion_matrix =confusion_matrix(ytest,ypred)
confusion_matrix

array([[42,  6],
       [17, 15]], dtype=int64)

In [19]:
classification_report(ytest,ypred)

'              precision    recall  f1-score   support\n\n           0       0.71      0.88      0.79        48\n           1       0.71      0.47      0.57        32\n\n    accuracy                           0.71        80\n   macro avg       0.71      0.67      0.68        80\nweighted avg       0.71      0.71      0.70        80\n'

In [20]:
TP=confusion_matrix[0,0]
FP=confusion_matrix[0,1]
TN=confusion_matrix[1,1]
FN=confusion_matrix[1,0]

In [21]:
print("TP:", TP)
print("FP:", FP)
print("TN:", TN)
print("FN:", FN)

TP: 42
FP: 6
TN: 15
FN: 17


In [22]:
print("Accuracy", accuracy_score(ytest,ypred))
print("Precision Score", precision_score(ytest,ypred))
print("Recall Score", recall_score(ytest,ypred))
print("F1 Score:", f1_score(ytest,ypred))

Accuracy 0.7125
Precision Score 0.7142857142857143
Recall Score 0.46875
F1 Score: 0.5660377358490566


In [23]:
accuracy = (TP+TN)/(TN+FN+TP+FP)
accuracy

0.7125

In [24]:
precision= TP/(TP+FP)
precision

0.875

In [25]:
recall= TP/(TP+FN)
recall

0.711864406779661

In [57]:
f1 = (2*recall*precision)/(recall+precision)
f1

0.7850467289719627

In [59]:
error = 1-accuracy
error

0.2875

# 10)
STUDY
HOURS

PASS/FAIL

29 0
15 0
33 1
48 1
39 1
2.Find the logistic regression for student if they study 25 and 42 hours

In [44]:
x=np.array([29,15,33,48,39]).reshape(-1,1)
y = np.array([0,0,1,1,1])

In [45]:
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state = 1)

In [46]:
model = LogisticRegression()

In [52]:
model.fit(x,y)

LogisticRegression()

In [53]:
model.predict([[25]])

array([0])

In [54]:
model.predict([[45]])

array([1])

In [55]:

y_pred = model.predict(x)

In [56]:
accuracy_score(y,y_pred)

1.0